Repository tshililopercy/Cpp_Github-Open-source_Inheritance_Analyzer, pull requests merged in 2022-10, with the labels that each got.

#13 Deleting Repo after extracting Inheritance information
  Data_Extraction_Process_Refractored.py
Labels: user-story, developer-story

#14 As a developer i can Identify hierarchies with inheritance information from a project
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  StoreData.py
Labels: developer-story

#15 Tests
  Data_Extraction_Process_Refractored.py
  tests/README.md
  tests/hybrid_inheritance.cpp
  tests/interf_inheritance.cpp
  tests/main.cpp
  tests/multiple_inheritance.cpp
  tests/test_Data_Extraction_Process_Refractored.py
Labels: enhancement, user-story

#17 Getting public interface, Added methods & abstract classes considering public and private inheritances with class member specifiers (public and private)
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  StoreData.py
  _tests__/test_Data_Extraction_Process_Refractored.py
Labels: user-story

#18 Extracting inheritance Data from header files
  Data_Extraction_Process_Refractored.py
Labels: user-story

#20 Adding Tool Multiple Repositories cloning Module and computing Hierarchies Data project by project.
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  GitHub_Search_And_Clone.py
  StoreData.py
  results.json
Labels: bug, user-story

#21 Data visualization
  AST_representation.py
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  Data_Presentation.py
  StoreData.py
  _tests__/test_Data_Extraction_Process_Refractored.py
  results.json
Labels: bug

#22 Added Tests (Extraction and inheritance computation) and Declaration Extraction To check client code for the inheritance usage.
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  Gui.py
  StoreData.py
  __mytests_/Inheritance_Hierachy/inheritance_hierachy_Level.cpp
  __mytests_/Multiple_inheritance/multiple_inheritance.cpp
  __mytests_/Single_inheritance/Derived_class_type/Single_Overriding.cpp
  __mytests_/Single_inheritance/Derived_class_type/Single_derived_class_type.cpp
  __mytests_/Single_inheritance/Single_Abstract_inheritance.cpp
  __mytests_/Single_inheritance/Single_Concrete_inheritance.cpp
  __mytests_/Single_inheritance/Single_Inheritance.cpp
  __mytests_/Single_inheritance/Single_interface_inheritance.cpp
  __mytests_/class_object.cpp/Single_class_properties.cpp
  __mytests_/class_object.cpp/class_data.cpp
  __mytests_/test_inheritance_Analysis.py
  results.json
Labels: user-story

#23 Storing The Hierachies Data to the Json file.
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  Gui.py
  HierachiesData.json
  StoreData.py
  __mytests_/README.md
  results.json
Labels: user-story

#24 Data visualization
  Data_Presentation.py
  HierachiesData.json
  StoreData.py
  results.json
Labels: user-story

#25 Added onto the data visualization to include more on abstract classes
  Data_Compute.py
  Data_Extraction_Process_Refractored.py
  StoreData.py
Labels: user-story

#26 Added User Interface, and Roots Data to the Hierarchy
  AnalysingProject.py
  Data_Extraction_Process_Refractored.py
  GitHub_Search_And_Clone.py
  Gui.py
  HierachiesData.json
  StoreData.py
  __mytests_/test_inheritance_Analysis.py
Labels: user-story

#27 Fixing Analysing Bug for Root class type
  AnalysingProject.py
Labels: bug, developer-story

#29 Extracting Project Declarations, to check the Types being used
  AnalysingProject.py
  Data_Compute.py
  Data_Extraction_Process_Refractored.py
  Gui.py
  HierachiesData.json
  StoreData.py
Labels: user-story

#44 Added checking for use of role modelling and enable results to show from GUI
  Data_Compute.py
  Gui.py
  HierachiesData.json
  StoreData.py
Labels: user-story

#45 Configuring in the working clang, to extract Cpp standard declarations correctly and execising DRY principle...Allowing a user to analyze already cloned repositories.
  AnalysingProject.py
  Data_Compute.py
  Data_Extraction_Process_Refractored.py
  Gui.py
  HierachiesData.json
Labels: developer-story
