Repository tshililopercy/Cpp_Github-Open-source_Inheritance_Analyzer, pull requests merged in 2022-11, with the labels that each got.

#47 Exposing public_pure_virtual_methods
  AnalysingProject.py
  Data_Compute.py
  Data_Extraction_Process_Refractored.py
  HierachiesData.json
  StoreData.py
Labels: user-story

#48 Added metrics to show novel and pure virtual methods per class
  Data_Compute.py
  Data_Extraction_Process_Refractored.py
  Gui.py
Labels: user-story

#49 Data visualization
  Data_Compute.py
  HierachiesData.json
Labels: user-story

#50 Resolving Multiple Root classes duplication issue, adding cloning 100 repositories and getting used classes
  AnalysingProject.py
  Data_Compute.py
  GitHub_Search_And_Clone.py
  HierachiesData.json
  Inheritance_Data_analysis.py
  StoreData.py
  Visualiser.py
Labels: bug, user-story

#53 Data visualization bug fixes to ensure hierarchies with information are analyzed
  Data_Compute.py
  HierachiesData.json
Labels: bug
